export const DRINKS_PENDING = 'DRINKS_PENDING';
export const DRINKS_SUCCESS = 'DRINKS_SUCCESS';
export const DRINKS_ERROR = 'DRINKS_ERROR';

export const DRINK_DETAILS_PENDING = 'DRINK_DETAILS_PENDING';
export const DRINK_DETAILS_SUCCESS = 'DRINK_DETAILS_SUCCESS';
export const DRINK_DETAILS_ERROR = 'DRINK_DETAILS_ERROR';

export const FOODS_PENDING = 'FOODS_PENDING';
export const FOODS_SUCCESS = 'FOODS_SUCCESS';
export const FOODS_ERROR = 'FOODS_ERROR';
