export const DRINKS_PENDING = 'DRINKS_PENDING';
export const DRINKS_SUCCESS = 'DRINKS_SUCCESS';
export const DRINKS_ERROR = 'DRINKS_ERROR';

export const FOOD_PENDING = 'FOOD_PENDING';
export const FOOD_SUCCESS = 'FOOD_SUCCESS';
export const FOOD_ERROR = 'FOOD_ERROR';
